# docker-compose up -d
# docker-compose down

version: "3.6"
networks:
  localdev:
    name: localdev

services:
  db-server:
    image: mcr.microsoft.com/mssql/server:2017-latest
    container_name: mssql
    networks:
      - localdev
    volumes:
      - sqlvolume:/var/opt/mssql      
  taxbox-api:
    entrypoint: ["./wait-for.sh", "mssql:1433", "-t", "120", "--", "dotnet", "Taxbox.Api.dll"]
    build:
      context: .
      dockerfile: src/Taxbox.Api/Dockerfile
    image: taxbox-api:local
    container_name: taxbox-api
    depends_on:
      - db-server
    networks:
      - localdev
    volumes:
      - ./etc/wait-for.sh:/app/wait-for.sh
  jaeger:
    container_name: jaeger
    image: jaegertracing/all-in-one:latest
    ports:
      - "6831:6831/udp"
      - "16686:16686"
    networks:
      - localdev

volumes:
  sqlvolume: